### PR TITLE
Changing timer

### PR DESCRIPTION
**Pull request by UshalNaidoo**
You need to click on the merge button.

I am trying to help you with your project

### CODE REVIEW

**Comment by rayliverified** [comment]
Please accept this pull request. A timer feature is greatly appreciated!

**Comment by searchy2** [comment]
Please accept this pull request. A timer feature is greatly appreciated!

**Comment by yadav-rahul** [comment]
@searchy2 This PR has conflicts with the main branch.

**Comment by UshalNaidoo** [comment]
@yadav-rahul That's because this branch was branched off another feature branch. Accept the Pull request for #12 first

**Pull request closed without merging**
