### PR TITLE
Added a default success toast and changing timer

### PR DESCRIPTION
**Pull request by UshalNaidoo**
Added a default success toast

### CODE REVIEW

**Comment by UshalNaidoo** [comment]
@yadav-rahul you will need to merge this change first, before the other pull request ( #9) in order to resolve the conflicts

**Comment by UshalNaidoo** [comment]
@yadav-rahul @harshit211997 When do you think this PR will be accepted?

**Comment by yadav-rahul** [comment]
@UshalNaidoo What is the use of passing _Toast Message_ twice ?

**Comment by UshalNaidoo** [comment]
@yadav-rahul The message is passed in once? The red lines are the code that has been removed, the green is the code that is added. There is a minus or plus in front of the line to indicate whether it was added or removed. If you have you not dealt with Pull Requests before, I can give you a quick run down of how it works.https://blog.codeship.com/github-code-review/

**Pull request closed without merging**
